print("today is a good weather")
print("i live in city")
print("rearrange the parentheses")
print("write parenthesese")
print("draw varietly trees")
print("this is incorect example")
print("he lossed money")
print("select the corect example")
print("i handled the bear")
print("i told you i like you GOA")
print("i surveyed who is the best football player")
print("i ensure my family")
print("which examples is similar")
print("this colour i explicit")